const weatherConditionGifs = {
  'Thunderstorm-d': 'ekY2RCWmHKnEIfGUcD',
  'Thunderstorm-n': 'o8A56JaNJQFSU',
  'Drizzle-d': 'QPsEnRasf0Vfa',
  'Drizzle-n': 'QPsEnRasf0Vfa',
  'Rain-d': 'PN23U6cVRWFFe',
  'Rain-n': 'PspWBxW4y3Kfu',
  'Snow-d': 'IiG1Moma7qgN2',
  'Snow-n': 'IiG1Moma7qgN2',
  'Smoke-d': 'xnRilboCF81EY',
  'Smoke-n': 'xnRilboCF81EY',
  'Haze-d': 'cZG3Tk1qVLTcA',
  'Haze-n': 'cZG3Tk1qVLTcA',
  'Fog-d': 'ZWRCWdUymIGNW',
  'Fog-n': 'ZWRCWdUymIGNW',
  'Sand-d': '4x814g81m1iTK',
  'Sand-n': '4x814g81m1iTK',
  'Dust-d': 'CJN2cdXD51Q2c',
  'Dust-n': 'CJN2cdXD51Q2c',
  'Ash-d': 'hhYYtVCNWz5Di',
  'Ash-n': 'hhYYtVCNWz5Di',
  'Squall-d': 'rsdDNSViCq8OQ',
  'Squall-n': 'rsdDNSViCq8OQ',
  'Tornado-d': 'ed8JGxnQmrke4',
  'Tornado-n': 'ed8JGxnQmrke4',
  'Clear-n': '7BurliewSdqFO',
  'Clear-d': 'Te7h0uqGNo0CY',
  'Clouds-n': 'QkwvkJc83E12g',
  'Clouds-d': 'Cn46Wi1Fvh11S',
};

export {
  weatherConditionGifs as
  default,
};